/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Source.Make_Evaluate;
import Source.mainPruebas;
import java.awt.Image;
import java.io.File;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author PC
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        //  Posicionar ventana en el centro
        this.setLocationRelativeTo(null);
        //  Colocar Imagen en la aplicacion
        ImageIcon imagen = new ImageIcon(getClass().getResource("\\images\\icon.png"));
        Icon logo = new ImageIcon(imagen.getImage().getScaledInstance(lblImagen.getWidth(), lblImagen.getHeight(), Image.SCALE_SMOOTH));
        lblImagen.setIcon(logo);
        
        taAG.setText("Estamos\nLlenando\nDe\nPuro\nTextoEstamos\nLlenando\nDe\nPuro\nTextoEstamos\nLlenando\nDe\nPuro\nTexto");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlUno = new javax.swing.JPanel();
        lblFileChooser = new javax.swing.JLabel();
        txtPath = new javax.swing.JTextField();
        btnFileChooser = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblMainTitle = new javax.swing.JLabel();
        btnInicio = new javax.swing.JButton();
        lblImagen = new javax.swing.JLabel();
        lblSubtitulo = new javax.swing.JLabel();
        lblIntro1 = new javax.swing.JLabel();
        lblIntro2 = new javax.swing.JLabel();
        lblIntro3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblAG = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taAG = new javax.swing.JTextArea();
        lblGen = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taGen = new javax.swing.JTextArea();
        lblInfoGen = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        taInfoGen = new javax.swing.JTextArea();
        lblResFit = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        taResFit = new javax.swing.JTextArea();
        btnVerArbol = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        btnGetGen = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Natural Trees\n");

        lblFileChooser.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        lblFileChooser.setText("Seleccione la silueta:");

        txtPath.setEditable(false);
        txtPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPathActionPerformed(evt);
            }
        });

        btnFileChooser.setText("...");
        btnFileChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFileChooserActionPerformed(evt);
            }
        });

        lblMainTitle.setFont(new java.awt.Font("Arial Rounded MT Bold", 2, 36)); // NOI18N
        lblMainTitle.setForeground(new java.awt.Color(51, 102, 0));
        lblMainTitle.setText("Natural Trees");

        btnInicio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnInicio.setText("Descifrar!");
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });

        lblSubtitulo.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblSubtitulo.setText("Parecen reales ¿Cierto?");

        lblIntro1.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        lblIntro1.setText("¿Desea que su computadora genere un arbol similar a uno real?");

        lblIntro2.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        lblIntro2.setText("Seleccione una silueta de un arbol, de un bmp monocromatico");

        lblIntro3.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        lblIntro3.setText("y observe los algoritmos hacer su magia");

        javax.swing.GroupLayout pnlUnoLayout = new javax.swing.GroupLayout(pnlUno);
        pnlUno.setLayout(pnlUnoLayout);
        pnlUnoLayout.setHorizontalGroup(
            pnlUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUnoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(pnlUnoLayout.createSequentialGroup()
                        .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pnlUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlUnoLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlUnoLayout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(pnlUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlUnoLayout.createSequentialGroup()
                                        .addComponent(lblMainTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(128, 128, 128)
                                        .addGroup(pnlUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblIntro1)
                                            .addComponent(lblIntro2)
                                            .addComponent(lblIntro3))
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(pnlUnoLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(pnlUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUnoLayout.createSequentialGroup()
                                                .addComponent(lblSubtitulo)
                                                .addGap(238, 238, 238))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUnoLayout.createSequentialGroup()
                                                .addComponent(lblFileChooser)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                        .addComponent(btnFileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtPath, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnInicio)
                                        .addGap(20, 20, 20))))))))
        );
        pnlUnoLayout.setVerticalGroup(
            pnlUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUnoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlUnoLayout.createSequentialGroup()
                        .addGroup(pnlUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(pnlUnoLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(lblMainTitle))
                            .addGroup(pnlUnoLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(lblIntro1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblIntro2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblIntro3)
                                .addGap(5, 5, 5)))
                        .addGroup(pnlUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlUnoLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(pnlUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtPath, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnInicio)
                                    .addComponent(btnFileChooser)
                                    .addComponent(lblFileChooser)))
                            .addGroup(pnlUnoLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(lblSubtitulo)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        lblAG.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        lblAG.setText("Algoritmo Genético");

        taAG.setEditable(false);
        taAG.setColumns(20);
        taAG.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        taAG.setRows(5);
        taAG.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        taAG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                taAGMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(taAG);

        lblGen.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        lblGen.setText("Generación a Observar");

        taGen.setEditable(false);
        taGen.setColumns(20);
        taGen.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        taGen.setRows(5);
        taGen.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane2.setViewportView(taGen);

        lblInfoGen.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        lblInfoGen.setText("Información Genética");

        taInfoGen.setEditable(false);
        taInfoGen.setColumns(20);
        taInfoGen.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        taInfoGen.setRows(5);
        taInfoGen.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane3.setViewportView(taInfoGen);

        lblResFit.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        lblResFit.setText("Resultado de Adaptabilidad");

        taResFit.setEditable(false);
        taResFit.setColumns(20);
        taResFit.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        taResFit.setRows(5);
        taResFit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane4.setViewportView(taResFit);

        btnVerArbol.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        btnVerArbol.setText("Ver Árbol");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btnGetGen.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        btnGetGen.setText("Seleccionar Generación");
        btnGetGen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetGenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlUno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGen)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGetGen)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(lblAG)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblInfoGen)
                    .addComponent(lblResFit)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jScrollPane4)
                            .addGap(18, 18, 18)
                            .addComponent(btnVerArbol))
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlUno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAG)
                            .addComponent(lblInfoGen, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                            .addComponent(jScrollPane3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGetGen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblResFit, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblGen, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(btnVerArbol)))
                        .addGap(42, 42, 42))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator2)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPathActionPerformed

    private void btnFileChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFileChooserActionPerformed
        JFileChooser fc = new JFileChooser();
        
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("*.bmp", "bmp");
        
        fc.setFileFilter(filtro);
        
        int selected = fc.showOpenDialog(this);
        
        if (selected == JFileChooser.APPROVE_OPTION){
            File theFile = fc.getSelectedFile();
            this.txtPath.setText(theFile.getAbsolutePath());
        }
        
        
    }//GEN-LAST:event_btnFileChooserActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        String thePath = txtPath.getText();
        if (thePath.isEmpty()){
            JOptionPane.showMessageDialog(null, "Por favor seleccione una imagen bmp", "Path invalido", JOptionPane.ERROR_MESSAGE);
        }else{
            System.out.println(thePath);
            double grade = Make_Evaluate.selection(thePath, ".\\src\\Source\\images\\fractal.bmp",400, 650, -90, 4, 4, 25, 2, 0, false, 45, 0, -45);
            System.out.println("The grade: "+grade);
        }
    }//GEN-LAST:event_btnInicioActionPerformed

    private void taAGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_taAGMouseClicked
        //No Usado
    }//GEN-LAST:event_taAGMouseClicked

    private void btnGetGenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetGenActionPerformed
        taGen.setText(taAG.getSelectedText());
    }//GEN-LAST:event_btnGetGenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFileChooser;
    private javax.swing.JButton btnGetGen;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnVerArbol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblAG;
    private javax.swing.JLabel lblFileChooser;
    private javax.swing.JLabel lblGen;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblInfoGen;
    private javax.swing.JLabel lblIntro1;
    private javax.swing.JLabel lblIntro2;
    private javax.swing.JLabel lblIntro3;
    private javax.swing.JLabel lblMainTitle;
    private javax.swing.JLabel lblResFit;
    private javax.swing.JLabel lblSubtitulo;
    private javax.swing.JPanel pnlUno;
    private javax.swing.JTextArea taAG;
    private javax.swing.JTextArea taGen;
    private javax.swing.JTextArea taInfoGen;
    private javax.swing.JTextArea taResFit;
    private javax.swing.JTextField txtPath;
    // End of variables declaration//GEN-END:variables
}
