/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package conversormoneda.Ventanas;

import Conversiones.Conversion;
import javax.swing.JOptionPane;

/**
 *
 * @author bryan
 */
public class ConversionUnidadesMetricas extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    Conversion micrometroMil = new Conversion("Micrómetros", "Mil",25.4);
    Conversion centimetroPulgada = new Conversion("Centrimetros", "Pulgada",2.54);
    Conversion centimetroPie = new Conversion("Centrimetros", "Pie",30.48);
    Conversion centimetroYarda = new Conversion("Centrimetros", "Yarda",91.44);
    Conversion metroRod = new Conversion("Metro", "Rod",5.0292);
    Conversion metroChain = new Conversion("Metro", "Chain",20.1168);  
    Conversion metroFurlong = new Conversion("Metro", "Furlong",201.168);  
    Conversion kilometroMilla = new Conversion("Kilometro", "Milla",1.609344);
    Conversion kilometroLegua = new Conversion("Kilometro", "Legua",4.828032);
    public ConversionUnidadesMetricas() {
       
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupConversion = new javax.swing.ButtonGroup();
        jLabelMenu = new javax.swing.JLabel();
        jLabelSeleccione = new javax.swing.JLabel();
        jComboBoxAmericanoMetro = new javax.swing.JComboBox<>();
        jRadioMetroAmericano = new javax.swing.JRadioButton();
        jRadioButtonAmericanoMetro = new javax.swing.JRadioButton();
        jComboBoxMetroAmericano = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldCantidad = new javax.swing.JTextField();
        jLabelResultado = new javax.swing.JLabel();
        jButtonConvertir = new javax.swing.JButton();
        jButtonAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menú Principal");
        setLocation(new java.awt.Point(540, 360));
        setName("framePrincipal"); // NOI18N
        setResizable(false);

        jLabelMenu.setFont(new java.awt.Font("DialogInput", 2, 24)); // NOI18N
        jLabelMenu.setText("Convertir Unidad Metrica");

        jLabelSeleccione.setFont(new java.awt.Font("DialogInput", 2, 14)); // NOI18N
        jLabelSeleccione.setText("Seleccione el tipo de conversión ");

        jComboBoxAmericanoMetro.setFont(new java.awt.Font("DialogInput", 2, 11)); // NOI18N
        jComboBoxAmericanoMetro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mil a Micrómetro", "Pulgada a Centrimetro", "Pie a Centrimetro", "Yarda a Centrimetro", "Rod a Metro", "Chain a Metro", "Furlong a Metro", "Milla a Kilómetro", "Legua a Kilómetro" }));

        buttonGroupConversion.add(jRadioMetroAmericano);
        jRadioMetroAmericano.setFont(new java.awt.Font("DialogInput", 2, 11)); // NOI18N
        jRadioMetroAmericano.setSelected(true);
        jRadioMetroAmericano.setText("Metro a Americano");
        jRadioMetroAmericano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioMetroAmericanoActionPerformed(evt);
            }
        });

        buttonGroupConversion.add(jRadioButtonAmericanoMetro);
        jRadioButtonAmericanoMetro.setFont(new java.awt.Font("DialogInput", 2, 11)); // NOI18N
        jRadioButtonAmericanoMetro.setText("Americano a Metro");

        jComboBoxMetroAmericano.setFont(new java.awt.Font("DialogInput", 2, 11)); // NOI18N
        jComboBoxMetroAmericano.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Micrómetro a Mil", "Centrimetro a Pulgada", "Centrimetro a Pie", "Centrimetro a Yarda", "Metro a Rod", "Metro a Chain", "Metro a Furlong", "Kilómetro a Milla", "Kilómetro a Legua" }));

        jLabel1.setFont(new java.awt.Font("DialogInput", 2, 11)); // NOI18N
        jLabel1.setText("Cantidad a convertir");

        jLabel2.setFont(new java.awt.Font("DialogInput", 2, 11)); // NOI18N
        jLabel2.setText("Resultado");

        jTextFieldCantidad.setFont(new java.awt.Font("DialogInput", 2, 11)); // NOI18N

        jLabelResultado.setFont(new java.awt.Font("DialogInput", 2, 11)); // NOI18N
        jLabelResultado.setText("Esperando reultado");

        jButtonConvertir.setFont(new java.awt.Font("DialogInput", 2, 11)); // NOI18N
        jButtonConvertir.setText("Convertir");
        jButtonConvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConvertirActionPerformed(evt);
            }
        });

        jButtonAtras.setFont(new java.awt.Font("DialogInput", 2, 11)); // NOI18N
        jButtonAtras.setText("Volver Atras");
        jButtonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonAmericanoMetro)
                    .addComponent(jRadioMetroAmericano))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxMetroAmericano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxAmericanoMetro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jButtonConvertir))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(jButtonAtras)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jLabelResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelMenu)
                            .addComponent(jLabelSeleccione))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelSeleccione)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxMetroAmericano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioMetroAmericano))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxAmericanoMetro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButtonAmericanoMetro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelResultado, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAtras)
                    .addComponent(jButtonConvertir))
                .addGap(9, 9, 9))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioMetroAmericanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioMetroAmericanoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioMetroAmericanoActionPerformed

    private void jButtonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtrasActionPerformed
        // TODO add your handling code here:
        MenuPrincipal menu = new MenuPrincipal();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonAtrasActionPerformed

    private void jButtonConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConvertirActionPerformed
        // TODO add your handling code here:
        if(jRadioMetroAmericano.isSelected()){
            try {
                double valor = Double.parseDouble(jTextFieldCantidad.getText());
                switch(jComboBoxMetroAmericano.getSelectedIndex()){
                    case 0 -> jLabelResultado.setText(micrometroMil.convertirPrincipalASecundario(valor)+"");
                    case 1 -> jLabelResultado.setText(centimetroPulgada.convertirPrincipalASecundario(valor)+"");
                    case 2 -> jLabelResultado.setText(centimetroPie.convertirPrincipalASecundario(valor)+"");
                    case 3 -> jLabelResultado.setText(centimetroYarda.convertirPrincipalASecundario(valor)+"");
                    case 4 -> jLabelResultado.setText(metroRod.convertirPrincipalASecundario(valor)+"");
                    case 5 -> jLabelResultado.setText(metroChain.convertirPrincipalASecundario(valor)+"");
                    case 6 -> jLabelResultado.setText(metroFurlong.convertirPrincipalASecundario(valor)+"");
                    case 7 -> jLabelResultado.setText(kilometroMilla.convertirPrincipalASecundario(valor)+"");
                    case 8 -> jLabelResultado.setText(kilometroLegua.convertirPrincipalASecundario(valor)+"");
                    default -> throw new AssertionError();
                }                
            }
            catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Debe introducir un número, verifique que no contenga letras u otro caracter");
            }
        }
        else{
            try {
                double valor = Double.parseDouble(jTextFieldCantidad.getText());
                switch(jComboBoxMetroAmericano.getSelectedIndex()){
                    case 0 -> jLabelResultado.setText(micrometroMil.convertirSecundarioAPrincipal(valor)+"");
                    case 1 -> jLabelResultado.setText(centimetroPulgada.convertirSecundarioAPrincipal(valor)+"");
                    case 2 -> jLabelResultado.setText(centimetroPie.convertirSecundarioAPrincipal(valor)+"");
                    case 3 -> jLabelResultado.setText(centimetroYarda.convertirSecundarioAPrincipal(valor)+"");
                    case 4 -> jLabelResultado.setText(metroRod.convertirSecundarioAPrincipal(valor)+"");
                    case 5 -> jLabelResultado.setText(metroChain.convertirSecundarioAPrincipal(valor)+"");
                    case 6 -> jLabelResultado.setText(metroFurlong.convertirSecundarioAPrincipal(valor)+"");
                    case 7 -> jLabelResultado.setText(kilometroMilla.convertirSecundarioAPrincipal(valor)+"");
                    case 8 -> jLabelResultado.setText(kilometroLegua.convertirSecundarioAPrincipal(valor)+"");
                    default -> throw new AssertionError();
                }                
            }
            catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Debe introducir un número, verifique que no contenga letras u otro caracter");
            }
        }
    }//GEN-LAST:event_jButtonConvertirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConversionUnidadesMetricas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConversionUnidadesMetricas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConversionUnidadesMetricas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConversionUnidadesMetricas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConversionUnidadesMetricas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupConversion;
    private javax.swing.JButton jButtonAtras;
    private javax.swing.JButton jButtonConvertir;
    private javax.swing.JComboBox<String> jComboBoxAmericanoMetro;
    private javax.swing.JComboBox<String> jComboBoxMetroAmericano;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelMenu;
    private javax.swing.JLabel jLabelResultado;
    private javax.swing.JLabel jLabelSeleccione;
    private javax.swing.JRadioButton jRadioButtonAmericanoMetro;
    private javax.swing.JRadioButton jRadioMetroAmericano;
    private javax.swing.JTextField jTextFieldCantidad;
    // End of variables declaration//GEN-END:variables
}
