/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package conversormoneda.Ventanas;

/**
 *
 * @author bryan
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    
    public MenuPrincipal() {
       
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupConversiones = new javax.swing.ButtonGroup();
        jLabelMenu = new javax.swing.JLabel();
        jRadioButtonMonedas = new javax.swing.JRadioButton();
        jRadioButtonOtros = new javax.swing.JRadioButton();
        jLabelSeleccione = new javax.swing.JLabel();
        jButtonEmpezar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menú Principal");
        setLocation(new java.awt.Point(540, 360));
        setName("framePrincipal"); // NOI18N
        setResizable(false);

        jLabelMenu.setFont(new java.awt.Font("DialogInput", 2, 24)); // NOI18N
        jLabelMenu.setText("Menú Principal");

        buttonGroupConversiones.add(jRadioButtonMonedas);
        jRadioButtonMonedas.setFont(new java.awt.Font("DialogInput", 2, 12)); // NOI18N
        jRadioButtonMonedas.setSelected(true);
        jRadioButtonMonedas.setText("Conversion de monedas");
        jRadioButtonMonedas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMonedasActionPerformed(evt);
            }
        });

        buttonGroupConversiones.add(jRadioButtonOtros);
        jRadioButtonOtros.setFont(new java.awt.Font("DialogInput", 2, 12)); // NOI18N
        jRadioButtonOtros.setActionCommand("");
        jRadioButtonOtros.setLabel("Conversion Metrica Estadounidense");

        jLabelSeleccione.setFont(new java.awt.Font("DialogInput", 2, 14)); // NOI18N
        jLabelSeleccione.setText("Seleccione el tipo de conversión ");

        jButtonEmpezar.setFont(new java.awt.Font("DialogInput", 2, 12)); // NOI18N
        jButtonEmpezar.setText("Empezar");
        jButtonEmpezar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonEmpezarMouseClicked(evt);
            }
        });
        jButtonEmpezar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEmpezarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jLabelMenu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonOtros)
                    .addComponent(jRadioButtonMonedas)
                    .addComponent(jLabelSeleccione))
                .addGap(52, 52, 52))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonEmpezar)
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabelMenu)
                .addGap(36, 36, 36)
                .addComponent(jLabelSeleccione)
                .addGap(27, 27, 27)
                .addComponent(jRadioButtonMonedas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonOtros)
                .addGap(18, 18, 18)
                .addComponent(jButtonEmpezar)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonMonedasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMonedasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonMonedasActionPerformed

    private void jButtonEmpezarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEmpezarMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButtonEmpezarMouseClicked

    private void jButtonEmpezarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEmpezarActionPerformed
        // TODO add your handling code here:
        if(jRadioButtonMonedas.isSelected()){
            ConversionMonedas monedas = new ConversionMonedas();
            monedas.setVisible(true);
            this.dispose();
        }
        else{
            ConversionUnidadesMetricas metricas = new ConversionUnidadesMetricas();
            metricas.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButtonEmpezarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupConversiones;
    private javax.swing.JButton jButtonEmpezar;
    private javax.swing.JLabel jLabelMenu;
    private javax.swing.JLabel jLabelSeleccione;
    private javax.swing.JRadioButton jRadioButtonMonedas;
    private javax.swing.JRadioButton jRadioButtonOtros;
    // End of variables declaration//GEN-END:variables
}
